/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: LENOVO
 *
 * Created on April 20, 2023, 3:30 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE                                1
#define INTERRUPT_FEATURE_DISABLE                               0

//#define INTERRUPT_PRIORITY_LEVELS_ENABLE               INTERRUPT_FEATURE_ENABLE

#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE         INTERRUPT_FEATURE_ENABLE

#define EXTERNAL_INTERRUPT_onchange_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE

#define INTERNAL_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#define TIMER0_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#define TIMER1_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

//#define TIMER2_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#define TIMER3_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#define CCP2_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#define EUSART_TX_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE

#define EUSART_RX_INTERRUPT_FEATURE_ENABLE   INTERRUPT_FEATURE_ENABLE


#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

